### ISSUE TITLE
網頁文案

### ISSUE THREAD

**Issue by vickychou99** [miterfrants/homo-iot-hub#2]
# Why
撰寫網頁文案
- 讓使用者了解我們的服務並註冊會員
- 讓設計師了解我們的服務，能設計出相關的頁面

# Task

- [x] 整理目標 TA 輪廓
- [x] 整理同性質的平台
- [x] 整理 SITEMAP 及頁面架構及文案內容
   - [x] INDEX
   - [x] SIGN UP
   - [x] SIGN IN
   - [x] RESET PASSWORD

# Check List

- 網址: https://docs.google.com/presentation/d/1UP6tSVh3SAGa9XQKU6QrVJdmwphUMuTj/edit#slide=id.gf34e103a2b_0_2
- 項目: 確認以下頁面內容，文案內容無誤
   - [x] INDEX
   - [x] SIGN UP
   - [x] SIGN IN
   - [x] RESET PASSWORD

**Comment by miterfrants** [comment]
# Pricing Plan

## Free 
- 1 Block
- 5 Devices
- Usage and Limit
  - 30 seconds/request/device
  - 50 M traffic/block

## Basic
- 10 Block
- 20 Devices/Block
- Usage and Limit
  - 3 seconds/request/device
  - 10 G traffic/block/day

## Advance 
- Unlimited Block
- Unlimited Devices/Block
- Usage and Limit
  - 1 seconds/request/device
  - 1T traffic/block/day

## Enterprise
- Contact us

**Comment by miterfrants** [comment]
Free 和 Basic 中間可以在一個炮灰方案
